<?php

/**
 * @file
 * Contains kuntafibase_now.module.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kuntafibase_now_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kuntafibase_now module.
    case 'help.page.kuntafibase_now':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Handle messaging and notifications for users') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_block_access().
 */
function kuntafibase_now_block_access(Block $block, $operation, AccountInterface $account) {
  /** @var Drupal\block\Entity\Block $block */
  if ((($block->id() == 'hidenowblock') || 
      ($block->id() == 'views_block__now_now')) &&
        ($operation == 'view')) {
    if (isset($_SESSION['hide_now'])) {
      return AccessResult::forbidden();
    }
  }
}

/**
 * Implements hook_theme().
 */
function kuntafibase_now_theme() {
  return [
    'kuntafibase_now' => [
      'render element' => 'children',
    ],
  ];
}
