<?php

/**
 * @file
 * Contains kuntafibase_basic_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kuntafibase_basic_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kuntafibase_basic_page module.
    case 'help.page.kuntafibase_basic_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Basic page supporting paragraphs and menu') . '</p>';
      return $output;

    default:
  }
}
