<?php

/**
 * @file
 * Contains kuntafibase_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kuntafibase_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kuntafibase_core module.
    case 'help.page.kuntafibase_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Core fields and taxonomies') . '</p>';
      return $output;

    default:
  }
}
