<?php

/**
 * @file
 * Contains kuntafibase_blog.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kuntafibase_blog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kuntafibase_blog module.
    case 'help.page.kuntafibase_blog':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Basic multiauthor blog') . '</p>';
      return $output;

    default:
  }
}
